const express=require("express"),fs=require("fs"),path=require("path"),crypto=require("crypto"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),helmet=require("helmet");
const app=express(),PORT=process.env.PORT||10000,JWT_SECRET=process.env.JWT_SECRET||"change-this-secret-before-production",DATA_DIR=path.join(__dirname,"data"),DB_FILE=path.join(DATA_DIR,"database.json");
if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true});
const initial={users:[],tasks:[],submissions:[],withdrawals:[],businessRequests:[],activity:[]};
if(!fs.existsSync(DB_FILE))fs.writeFileSync(DB_FILE,JSON.stringify(initial,null,2));
const db=()=>JSON.parse(fs.readFileSync(DB_FILE,"utf8"));const save=d=>{const t=DB_FILE+".tmp";fs.writeFileSync(t,JSON.stringify(d,null,2));fs.renameSync(t,DB_FILE)};const id=()=>crypto.randomBytes(12).toString("hex");
app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:"1mb"}));app.use(express.urlencoded({extended:true}));
function auth(req,res,next){try{const h=req.headers.authorization||"";if(!h.startsWith("Bearer "))return res.status(401).json({error:"Login required"});req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch(e){res.status(401).json({error:"Invalid or expired session"})}}
function admin(req,res,next){if(req.user.role!=="admin")return res.status(403).json({error:"Admin only"});next()}
function safe(u){return {id:u.id,name:u.name,email:u.email,role:u.role,balance:u.balance,createdAt:u.createdAt}}
function seed(){let d=db();if(!d.tasks.length){d.tasks=[
{id:id(),title:"Image Verification",description:"Check whether the image contains a car.",reward:2,type:"yesno",imageUrl:"https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=80",active:true,source:"platform",createdAt:new Date().toISOString()},
{id:id(),title:"Product Verification",description:"Check whether the product shown is a shoe.",reward:3,type:"yesno",imageUrl:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",active:true,source:"platform",createdAt:new Date().toISOString()},
{id:id(),title:"Text Verification",description:"Check whether the image contains readable text.",reward:4,type:"yesno",imageUrl:"https://images.unsplash.com/photo-1456324504439-367cee3b3c32?auto=format&fit=crop&w=900&q=80",active:true,source:"platform",createdAt:new Date().toISOString()}
]};save(d)}seed();

app.get("/api/health",(req,res)=>res.json({ok:true,service:"Mobile Work Marketplace"}));
app.post("/api/register",async(req,res)=>{let {name,email,password}=req.body;name=String(name||"").trim();email=String(email||"").trim().toLowerCase();password=String(password||"");if(name.length<2||name.length>80)return res.status(400).json({error:"Enter a valid name"});if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return res.status(400).json({error:"Enter a valid email"});if(password.length<6)return res.status(400).json({error:"Password must be at least 6 characters"});let d=db();if(d.users.some(u=>u.email===email))return res.status(409).json({error:"Account already exists. Please login."});const u={id:id(),name,email,password:await bcrypt.hash(password,12),role:"user",balance:0,createdAt:new Date().toISOString()};d.users.push(u);d.activity.push({id:id(),type:"register",userId:u.id,at:new Date().toISOString()});save(d);res.json({user:safe(u),token:jwt.sign({id:u.id,email:u.email,role:u.role},JWT_SECRET,{expiresIn:"7d"})})});
app.post("/api/login",async(req,res)=>{const email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||"");let d=db(),u=d.users.find(x=>x.email===email);if(!u||!(await bcrypt.compare(password,u.password)))return res.status(401).json({error:"Invalid email or password"});res.json({user:safe(u),token:jwt.sign({id:u.id,email:u.email,role:u.role},JWT_SECRET,{expiresIn:"7d"})})});
app.get("/api/me",auth,(req,res)=>{let d=db(),u=d.users.find(x=>x.id===req.user.id);if(!u)return res.status(404).json({error:"User not found"});res.json({user:safe(u)})});

app.get("/api/tasks",auth,(req,res)=>{let d=db();res.json({tasks:d.tasks.filter(t=>t.active).map(t=>({...t}))})});
app.post("/api/tasks/:taskId/submit",auth,(req,res)=>{let d=db(),u=d.users.find(x=>x.id===req.user.id),t=d.tasks.find(x=>x.id===req.params.taskId&&x.active);if(!t)return res.status(404).json({error:"Task not found"});const exists=d.submissions.find(s=>s.taskId===t.id&&s.userId===u.id&&s.status!=="rejected");if(exists)return res.status(409).json({error:"You already submitted this task"});const answer=String(req.body.answer||"").trim().toLowerCase();if(!["yes","no"].includes(answer))return res.status(400).json({error:"Choose Yes or No"});const s={id:id(),taskId:t.id,userId:u.id,answer,reward:t.reward,status:"pending",createdAt:new Date().toISOString()};d.submissions.push(s);d.activity.push({id:id(),type:"submission",userId:u.id,submissionId:s.id,at:new Date().toISOString()});save(d);res.json({message:"Submitted for review",submission:s})});
app.get("/api/submissions",auth,(req,res)=>{let d=db();res.json({submissions:d.submissions.filter(s=>s.userId===req.user.id).map(s=>{const t=d.tasks.find(x=>x.id===s.taskId);return {...s,taskTitle:t?t.title:"Task"}})})});

app.post("/api/business/request",auth,(req,res)=>{let {businessName,title,description,reward,totalTasks}=req.body;businessName=String(businessName||"").trim();title=String(title||"").trim();description=String(description||"").trim();reward=Number(reward);totalTasks=Number(totalTasks);if(!businessName||!title||!description||!Number.isFinite(reward)||reward<1||reward>10000||!Number.isInteger(totalTasks)||totalTasks<1||totalTasks>100000)return res.status(400).json({error:"Enter valid business task details"});let d=db(),r={id:id(),userId:req.user.id,businessName,title,description,reward,totalTasks,status:"pending",createdAt:new Date().toISOString()};d.businessRequests.push(r);save(d);res.json({message:"Business request sent to admin",request:r})});

app.post("/api/withdraw",auth,(req,res)=>{const amount=Number(req.body.amount);let d=db(),u=d.users.find(x=>x.id===req.user.id);if(!Number.isInteger(amount)||amount<100)return res.status(400).json({error:"Minimum withdrawal is 100 points"});if(amount>u.balance)return res.status(400).json({error:"Insufficient balance"});const pending=d.withdrawals.filter(w=>w.userId===u.id&&w.status==="pending").reduce((a,w)=>a+w.amount,0);if(amount+pending>u.balance)return res.status(400).json({error:"You already have pending withdrawals"});u.balance-=amount;const w={id:id(),userId:u.id,amount,status:"pending",createdAt:new Date().toISOString()};d.withdrawals.push(w);save(d);res.json({message:"Withdrawal request created",withdrawal:w})});

app.get("/api/admin/summary",auth,admin,(req,res)=>{let d=db();res.json({users:d.users.length,tasks:d.tasks.length,submissions:d.submissions.filter(x=>x.status==="pending").length,withdrawals:d.withdrawals.filter(x=>x.status==="pending").length,businessRequests:d.businessRequests.filter(x=>x.status==="pending").length})});
app.get("/api/admin/submissions",auth,admin,(req,res)=>{let d=db();res.json({submissions:d.submissions.map(s=>{const u=d.users.find(x=>x.id===s.userId),t=d.tasks.find(x=>x.id===s.taskId);return {...s,user:u?{id:u.id,name:u.name,email:u.email}:null,taskTitle:t?t.title:"Task"}})})});
app.post("/api/admin/submissions/:sid/review",auth,admin,(req,res)=>{let decision=String(req.body.decision||"");if(!["approve","reject"].includes(decision))return res.status(400).json({error:"Invalid decision"});let d=db(),s=d.submissions.find(x=>x.id===req.params.sid);if(!s||s.status!=="pending")return res.status(404).json({error:"Submission not found or already reviewed"});const u=d.users.find(x=>x.id===s.userId);s.status=decision==="approve"?"approved":"rejected";s.reviewedAt=new Date().toISOString();if(s.status==="approved")u.balance+=s.reward;save(d);res.json({message:"Submission reviewed"})});
app.get("/api/admin/withdrawals",auth,admin,(req,res)=>{let d=db();res.json({withdrawals:d.withdrawals.map(w=>{const u=d.users.find(x=>x.id===w.userId);return {...w,user:u?{id:u.id,name:u.name,email:u.email}:null}})})});
app.post("/api/admin/withdrawals/:wid/review",auth,admin,(req,res)=>{const decision=String(req.body.decision||"");if(!["paid","reject"].includes(decision))return res.status(400).json({error:"Invalid decision"});let d=db(),w=d.withdrawals.find(x=>x.id===req.params.wid);if(!w||w.status!=="pending")return res.status(404).json({error:"Withdrawal not found or already reviewed"});const u=d.users.find(x=>x.id===w.userId);w.status=decision==="paid"?"paid":"rejected";w.reviewedAt=new Date().toISOString();if(decision==="reject")u.balance+=w.amount;save(d);res.json({message:"Withdrawal reviewed"})});
app.get("/api/admin/business-requests",auth,admin,(req,res)=>{let d=db();res.json({requests:d.businessRequests.map(r=>{const u=d.users.find(x=>x.id===r.userId);return {...r,user:u?{id:u.id,name:u.name,email:u.email}:null}})})});
app.post("/api/admin/business-requests/:rid/review",auth,admin,(req,res)=>{const decision=String(req.body.decision||"");if(!["approve","reject"].includes(decision))return res.status(400).json({error:"Invalid decision"});let d=db(),r=d.businessRequests.find(x=>x.id===req.params.rid);if(!r||r.status!=="pending")return res.status(404).json({error:"Request not found"});r.status=decision==="approve"?"approved":"rejected";r.reviewedAt=new Date().toISOString();if(decision==="approve"){d.tasks.push({id:id(),title:r.title,description:r.description,reward:r.reward,type:"yesno",imageUrl:"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=80",active:true,source:"business",businessName:r.businessName,createdAt:new Date().toISOString()})}save(d);res.json({message:"Business request reviewed"})});
app.get("/api/admin/users",auth,admin,(req,res)=>{let d=db();res.json({users:d.users.map(safe)})});

app.get("/",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
app.use(express.static(path.join(__dirname,"public")));
app.listen(PORT,()=>console.log("Mobile Work Marketplace running on "+PORT));